### ISSUE TITLE
Floats

### ISSUE THREAD

**Issue by Hodo-** [Hodo-/dsn1674-assignment-5#1]
@thomasjbradley I have run into three issues that I can't seem to figure out, which are: hover, figure-captions, and legume data.

Hover - When you hover your mouse over one of the three links, the box that appears is small and it doesn't fill the whole box. 

Figure-captions - I can't get the text aligned properly and I don't know how either. I tried to use float and everything else.

Legume data - Similar issue as above. Can't get it aligned properly.

**Comment by thomasjbradley** [comment]
_Nav hover_

Remove the padding from the `li` elements, and add it to the `a` tags.
Then adjust the `a` tags' `display` property so it will fill the whole `li`.

---

_Figure/captions_

Each image should have its own `figure` element with the text inside the `figcaption`. Then the `figure` gets floated.

---

_Legume data_

Double check if there's margins or paddings on the images.

**Comment by Hodo-** [comment]
The nav hover and figure/captions are now fixed, but I am still struggling with Legume data. I can't seem to get rid of the margins of the images no matter what I do. I also can't get rid of the padding for the h2 title "Famous Legumes".

**Comment by thomasjbradley** [comment]
_Legume data_

I don't remember if it was the case before, but a `dl` isn't going to get the result you want, use a `ul` instead.

---

_Heading_

That's a clearing/clearfix issue.
